version: '3.5'
services:
  table_extractor:
    image: table_extractor:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./db:/db"
      - "./logs:/logs"
      - "./downloads:/downloads"
    depends_on:
      - database
  database:
    image: mongo:4.4.4
    ports:
      - 27017:27017
    volumes:
    - "./arxiv-data:/data/db"